# Generated by Django 2.1.7 on 2019-04-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsurvey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_activate',
            field=models.BooleanField(default=False, verbose_name='是否允许选择'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
