# Generated by Django 2.1.7 on 2019-04-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsurvey', '0002_auto_20190415_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualifiedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='电子邮箱')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('student_id', models.CharField(max_length=255, verbose_name='学号')),
                ('school', models.CharField(max_length=255, verbose_name='学院')),
                ('gender', models.CharField(max_length=1, verbose_name='性别')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='site',
            name='students',
            field=models.ManyToManyField(to='gsurvey.QualifiedUser'),
        ),
    ]
