# Generated by Django 2.1.7 on 2019-04-16 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsurvey', '0003_auto_20190416_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QualifiedUser',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='test', max_length=1, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_activate',
            field=models.BooleanField(default=False, verbose_name='是否允许选择'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='test', max_length=255, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='test', max_length=255, verbose_name='学院'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(default='test', max_length=255, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='site',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test', max_length=254, unique=True, verbose_name='电子邮箱'),
        ),
    ]
